language: ruby
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
branches:
  only:
    - master
